### ISSUE TITLE
销售单据不能关联查询出库和销售退单

### ISSUE THREAD

**Issue by lonelyleaves** [osbzr/gooderp_addons#1421]
操作系统及版本:ubuntu14.04 server
----
问题:
----
1.销售单据不能关联查看所有的移库单

2.销售单出库以后再入库会报错
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/gooderp_addons/sell/models/sell_delivery.py", line 416, in sell_delivery_done
    record._line_qty_write()
  File "/opt/odoo/gooderp_addons/sell/models/sell_delivery.py", line 252, in _line_qty_write
    line.sell_line_id.quantity_out -= line.goods_qty
  File "/opt/odoo/odoo/fields.py", line 885, in __set__
    record.ensure_one()
  File "/opt/odoo/odoo/models.py", line 4825, in ensure_one
    raise ValueError("Expected singleton: %s" % self)

ValueError: Expected singleton: sell.order.line()

**Comment by lonelyleaves** [comment]
已经更新最新的代码

**Comment by Judystudy** [comment]
已测试，可以关闭
