### ISSUE TITLE
升级出错

### ISSUE THREAD

**Issue by starboykm** [osbzr/gooderp_addons#1625]
操作系统及版本:
---- Windows绿色版 & Linux 绿色版
重现问题的步骤:
----
1.  绿色新版，恢复数据，出现错误
Traceback (most recent call last):
  File "/home/GoodERP/GoodERP_New/openobject/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/addons/web/controllers/main.py", line 866, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/addons/web/controllers/main.py", line 858, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/GoodERP/GoodERP_New/gooderp_addons/home_page/models/home_page.py", line 111, in get_action_url
    self.construction_action_url_list(action, action_url_list)
  File "/home/GoodERP/GoodERP_New/gooderp_addons/home_page/models/home_page.py", line 82, in construction_action_url_list
    compute_value = sum([res_model_obj[field_compute] for res_model_obj in res_model_objs])
  File "/home/GoodERP/GoodERP_New/openobject/odoo/models.py", line 5177, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/GoodERP/GoodERP_New/openobject/odoo/fields.py", line 869, in __get__
    self.determine_value(record)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/fields.py", line 971, in determine_value
    record._prefetch_field(self)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/models.py", line 3051, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/home/GoodERP/GoodERP_New/openobject/odoo/models.py", line 2991, in read
    self._read_from_database(stored, inherited)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/models.py", line 3119, in _read_from_database
    cr.execute(query_str, params)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column buy_receipt.delivery_fee does not exist
LINE 1: ...s "debt","buy_receipt"."is_return" as "is_return","buy_recei...

2. 升级Base 数据库，不成功。

Traceback (most recent call last):
  File "/home/GoodERP/GoodERP_New/openobject/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/addons/web/controllers/main.py", line 870, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/GoodERP/GoodERP_New/openobject/odoo/addons/web/controllers/main.py", line 858, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/addons/base/module/module.py", line 527, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/modules/loading.py", line 333, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/modules/loading.py", line 235, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/modules/loading.py", line 103, in load_module_graph
    migrations = odoo.modules.migration.MigrationManager(cr, graph)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/modules/migration.py", line 49, in __init__
    self._get_files()
  File "/home/GoodERP/GoodERP_New/openobject/odoo/modules/migration.py", line 64, in _get_files
    self.migrations[pkg.name]['module'] = get_module_filetree(pkg.name, 'migrations') or {}
  File "/home/GoodERP/GoodERP_New/openobject/odoo/modules/module.py", line 187, in get_module_filetree
    files = odoo.tools.osutil.listdir(path, True)
  File "/home/GoodERP/GoodERP_New/openobject/odoo/tools/osutil.py", line 28, in listdir
    for root, dirs, files in walksymlinks(dir):
  File "/home/GoodERP/GoodERP_New/openobject/odoo/tools/osutil.py", line 38, in walksymlinks
    for dirpath, dirnames, filenames in os.walk(top, topdown, onerror):
  File "./runtime/python/bin/../../python/lib/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "./runtime/python/bin/../../python/lib/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "./runtime/python/bin/../../python/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 15: ordinal not in range(128)

3. 刷新后出现500内部错误

...

截图:
恢复数据库后错误：
![image](https://user-images.githubusercontent.com/34362347/34593630-13481502-f207-11e7-8924-6996a9c8aaaf.png)

升级Base数据库出错：
![image](https://user-images.githubusercontent.com/34362347/34593840-672fb0b6-f208-11e7-9d0d-78594e5158cb.png)

出现500内部错误，无法再打开网页：
![image](https://user-images.githubusercontent.com/34362347/34593870-9251412e-f208-11e7-8c01-2872214cd0b6.png)

期望的结果: 如何升级？
----

**Comment by GoodERPJeff** [comment]
可以print一下b是什么东西，怎么会有中文？
